### ISSUE TITLE
Croatian translation

### ISSUE THREAD

**Issue by Missannth** [AugurProject/whitepaper#42]
Croatian translation ongoing

**Comment by ghost** [comment]
Reserved. Thanks!

**Comment by ghost** [comment]
Hi @Missannth, how is this going?

**Comment by Missannth** [comment]
Hi,
It's going fine altogether. I had some issues with local characters not showing up but resolved them. Is there a contact address for questions or should i post them here?
Kind regards,
Missannth

-------- Original Message --------

**Comment by ghost** [comment]
@Missannth I recommend coming in the #translation channel of our Discord:

augur.net/invite
