### ISSUE TITLE
Vietnamese

### ISSUE THREAD

**Issue by Leodalat** [AugurProject/whitepaper#43]
Whitepaper in Vietnamese 
https://www.overleaf.com/read/hbdwcwyzwrtz

**Comment by tomkysar** [comment]
Confirmed. Thanks!

**Comment by tomkysar** [comment]
Hi @Leodalat, how is this going?

**Comment by Leodalat** [comment]
Hi. I'm working. It will be completed soon

2018-05-09 9:29 GMT+07:00 Tom Kysar <notifications@github.com>:

**Comment by tomkysar** [comment]
Pinged on Discord
