### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by dalqa** [AugurProject/whitepaper#44]
Turkish translation is ongoing. I'll keep y'all posted. ***It's %35 done already.

Minor issue; When i use oveeleaf's task some turkish letters (like ğ,ş,ı and ç) disappears. So for now I translate everything on my own word page, I may ask some help later on to put them in to the task. ,

Thanks

-dalqa

**Comment by ghost** [comment]
Reserved, great! You can come join the #translations channel in our [Discord](http://augur.net/invite) and ask other translators what they've done for special characters.

**Comment by dalqa** [comment]
%95 almost....

**Comment by ghost** [comment]
@dalqa great!

**Comment by dalqa** [comment]
Done! I translated on .doc so I'll transfer into overleaf today. I am not computer savy so I'll get some help from my friend not to make mistake. I'll post overleaf link with diagrams tonight.

**Comment by dalqa** [comment]
https://www.overleaf.com/16316084hkfyycrtkpqs

I have a small issue, I can't change definition, observation, theorem and lemma to Turkish. System fails when i play with codes and i cant delete them since they are written in the beginning, I have no coding knowledge so for sure it is something pretty easy but I could not fix it. Can anybody help me?
BTW to make Turkish letters visible I used codes:
\usepackage[utf8]{inputenc}
\usepackage{eurosym}

I hope that's fine. It took much longer than i expected to convert .doc to overleaf..

**Comment by dalqa** [comment]
Thanks to @CBB for helping me out with codes. Here is read only copy of Turkish translation. 
https://www.overleaf.com/read/spnqpnkhhxwn

As i mentioned above; \usepackage[utf8]{inputenc}
\usepackage{eurosym} added to make Turkish special characters visible.

3G4bakwAKWw8cxDzZcoBSXWc9WpcFT8TiK (BITCOIN WALLET)

**Comment by ghost** [comment]
Pinged on Discord.
