### ISSUE TITLE
Polish Translation

### ISSUE THREAD

**Issue by cryptomental** [AugurProject/whitepaper#46]
Polish translation ongoing.

**Comment by cryptomental** [comment]
@tomkysar I had to add to the LateX document header the following directives:

```
\usepackage{polski}
\usepackage[utf8]{inputenc}
```
to allow Overleaf to correctly parse Polish diacritical marks ą, ę, ś, ć and generate PDF with letters containing those marks. I hope adding those directives is fine, could you please confirm?

**Comment by ghost** [comment]
Confirmed you for this language. Adding that to make Polish work is great! Thanks.

**Comment by cryptomental** [comment]
Thanks!

**Comment by ghost** [comment]
Hi @cryptomental , how is this going?

**Comment by cryptomental** [comment]
Hi @tomkysar  I am at 7th page already. In the beginning the process was a bit slow as I had to adjust the vocabulary. I think I got it right. Now the translation proceeds faster and I will finish within the allocated window.

**Comment by cryptomental** [comment]
Btw. I learned *a lot* about Augur doing this translation. I will try to give updates on my progress every 2-3 days.

**Comment by cryptomental** [comment]
1.5 page more. I will speed up this week.

**Comment by cryptomental** [comment]
6.5 pages left.

**Comment by cryptomental** [comment]
An important milestone reached. The main part of the Polish translation was completed. Appendixes are in progress.

**Comment by cryptomental** [comment]
Polish translation with appendixes has been completed. Proofreading in progress!
I hope to open a PR over the weekend.

**Comment by cryptomental** [comment]
@tomkysar The Polish translation is completed !

[augur-whitepaper-PL.pdf](https://github.com/AugurProject/whitepaper/files/2019830/augur-whitepaper-PL.pdf)
![overview](https://user-images.githubusercontent.com/20819151/40273508-63452f12-5bc1-11e8-835d-00e7508fa930.png)
![reporting](https://user-images.githubusercontent.com/20819151/40273509-636328fa-5bc1-11e8-91aa-18d3d84f5643.png)

* Overleaf link 
https://www.overleaf.com/15730228kbygnntnrsps#/59829657/

* My BTC address
3AvY4iSGa1RuGiHERnU5kdQwNgjM4AXruA

**Comment by ghost** [comment]
Paid, thank you for your work!

**Comment by cryptomental** [comment]
Thanks a lot @tomkysar . It took me a lot of time but I really enjoyed it!
