### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by comodoro** [AugurProject/whitepaper#47]
I would like to reserve Czech translation

**Comment by ghost** [comment]
Confirmed. Thanks!

**Comment by ghost** [comment]
Hi @comodoro, how is this going?

**Comment by comodoro** [comment]
Thanks for the nudge, I have made myself finish it today, but it is still not proofread and I am not happy with (=I will change) some of the translations. Some of them sound strange and some outright ridiculous. The fact that there is absolutely no blockchain terminology in my language does not help

**Comment by comodoro** [comment]
Czech translation is complete, I am not sure where to post the Overleaf link. Is it not publicly editable? @tomkysar ?

**Comment by comodoro** [comment]
Oh, there are read only links. Here it is:

https://www.overleaf.com/read/nqjrssqcgrpc

My ETH address is 0x2528f68b0f0d2d2d7f811a7ecf1c3fb082e87d84

**Comment by comodoro** [comment]
One more thing done, according to Czech typography rules, single-letter prepositions are not allowed at ends of lines. Used the `vlna` program to put nonbreaking spaces to the appropriate places

**Comment by comodoro** [comment]
This is basically how I adjusted the source as far as I rememmber, to be sure a diff can be done for lines starting with backslashes:

Packages:

```
\usepackage[czech]{babel}
\usepackage[utf8]{inputenc}
```

Before maketitle ("and" and "Date" in title, Acknowledgements):

```
\renewcommand\acknowledgmentsname{Poděkování}

\makeatletter
\def\Dated@name{Datum: }
\def\andname{a} \def\@listcomma@comma{\@ifnum{\@tempcnta>\tw@}{,}{}}
\makeatother
```

Throughout the document: replaced English quotes with `\uv{}`

Localized bibliography style (some .bst file must be placed among project files). Otherwise bibliography will be in English:
```
\bibliographystyle{czechiso}
```

**Comment by ghost** [comment]
Paid, thank you! The instructions are great and I will direct future translators to your references above.
