### ISSUE TITLE
Lithuanian Translation

### ISSUE THREAD

**Issue by simas21** [AugurProject/whitepaper#5]
Lithuanian Translation ongoing

**Comment by ghost** [comment]
Reserved. You're allowed two translations, we're looking for native speakers, not someone to use some service / other to mass translate into 40 languages, we hope you understand. 

You are more than welcome to do Lithuanian. Reserved.

Tom

**Comment by simas21** [comment]
Hi Tom,

I own a translation company and I have quite a few native people willing to translate the whitepaper to various languages. Would the be ok?

**Comment by ghost** [comment]
Hi Simas, 

Please contact me in our Discord, at @tk. 

augur.net/invite

Thanks!

**Comment by simas21** [comment]
80% done. Should be done by the end of the week.

**Comment by simas21** [comment]
All done. https://www.overleaf.com/15653083kkftpcgkmmmc#/59488612/

ETH address: 0xf5e163dbc1c5b0aecc04c134075696cc61742f8a

**Comment by ghost** [comment]
Complete, thanks!
