### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by simas21** [AugurProject/whitepaper#6]
French Translation ongoing

**Comment by ghost** [comment]
Reserved. You're allowed two translations, we're looking for native speakers, not someone to use some service / other to mass translate into 40 languages, we hope you understand. 

You are more than welcome to do French. Reserved.

Tom

**Comment by simas21** [comment]
Dear Tom,

the symbols like é disappear in the preview in the overleaf. Do you know how to solve that problem?

**Comment by ghost** [comment]
@simas21 Come join the #translations channel in our [Discord](http://augur.net/invite), other translators will be able to help!

**Comment by ghost** [comment]
Hi @simas21, how is this going?

**Comment by simas21** [comment]
Hi Tom,

my French translator has left on the sick leave. I do not think we'll cover this on time. We'll work on Lithuanian translation currently and if I have any other translators available I will let you know.
